### ISSUE TITLE
Some glitches in some ROMs

### ISSUE THREAD

**Issue by kastorcode** [kastorcode/chip-8-emulator-typescript#1]
In Airplane.ch8 ROM, the first gameplay is normal:
\
![ss0](https://user-images.githubusercontent.com/34523460/188123007-ba366f2f-0414-4dc6-9cb8-b06c679ee94f.png)
\
But in the second, we have some glitches on the canvas:
\
![ss1](https://user-images.githubusercontent.com/34523460/188123013-68957574-a3a7-4a90-88f7-ad4709b04901.png)
\
\
The Addition Problems [Paul C. Moews].ch8 ROM does not work appositely:
\
![ss2](https://user-images.githubusercontent.com/34523460/188123015-d44af51a-8aad-4ffc-abe0-b6917f2e8152.png)
\
\
Why? How to solve this?

**Comment by griffi-gh** [comment]
Try cpu tests/test suites

**Comment by kastorcode** [comment]
The commit b9f523fb02b92a4dec426699969ec6ad973bf2ff solve the bug.
